-- Alfreej Inventory — Seed Data
-- Run AFTER mysql_schema.sql in phpMyAdmin

-- Categories
INSERT IGNORE INTO categories (name) VALUES
  ('Baking & Flour'),
  ('Beverages'),
  ('Cleaning & Kitchen Tools'),
  ('Dairy & Cheese'),
  ('Disposables & Packaging'),
  ('General Groceries'),
  ('Meat & Poultry'),
  ('Oils & Creams'),
  ('Pasta & Grains'),
  ('Sauces, Condiments & Pastes'),
  ('Spices & Seasonings'),
  ('Vegetables & Fruits');

-- Ingredients (127 items)
INSERT IGNORE INTO ingredients (id, name, category, current_qty, min_limit, unit, location) VALUES
-- Baking & Flour
('KIT-001','ARABIC FLOUR','Baking & Flour',15,3,'KG','Maamoura Kitchen'),
('KIT-002','FLOUR NO. 1','Baking & Flour',0,2,'KG','Maamoura Kitchen'),
('KIT-003','FLOUR NO. 3','Baking & Flour',0,1,'KG','Maamoura Kitchen'),
('KIT-004','HAREES','Baking & Flour',5,2,'KG','Maamoura Kitchen'),
('KIT-005','ITALIAN FLOUR','Baking & Flour',25,5,'KG','Maamoura Kitchen'),
('KIT-006','SAGOU','Baking & Flour',0,1,'KG','Maamoura Kitchen'),
('KIT-007','SEMOLINA','Baking & Flour',0,1,'KG','Maamoura Kitchen'),
('KIT-008','YEAST','Baking & Flour',0,2,'PCS','Maamoura Kitchen'),
-- Beverages
('KIT-009','KINZA COLA','Beverages',20,10,'PCS','Maamoura Kitchen'),
('KIT-010','KINZA DIET','Beverages',20,10,'PCS','Maamoura Kitchen'),
('KIT-011','KINZA LEMON','Beverages',16,10,'PCS','Maamoura Kitchen'),
('KIT-012','KINZA ORANGE','Beverages',13,10,'PCS','Maamoura Kitchen'),
('KIT-013','ROSE WATER','Beverages',6,2,'PCS','Maamoura Kitchen'),
('KIT-014','STAFF WATER','Beverages',16,4,'PCS','Maamoura Kitchen'),
('KIT-015','TEA','Beverages',0,0,'PCS','Maamoura Kitchen'),
('KIT-016','VIMTO','Beverages',0,0,'PCS','Maamoura Kitchen'),
-- Cleaning & Kitchen Tools
('KIT-017','CLOROX','Cleaning & Kitchen Tools',2,0,'GALLON','Maamoura Kitchen'),
('KIT-018','DISHWASHING LIQUID','Cleaning & Kitchen Tools',2,1,'GALLON','Maamoura Kitchen'),
('KIT-019','HAND WASH','Cleaning & Kitchen Tools',0,1,'PCS','Maamoura Kitchen'),
('KIT-020','SPONGE','Cleaning & Kitchen Tools',6,2,'PCS','Maamoura Kitchen'),
('KIT-021','WIPER','Cleaning & Kitchen Tools',0,0,'PCS','Maamoura Kitchen'),
-- Dairy & Cheese
('KIT-022','BUTTER','Dairy & Cheese',1,0,'KG','Maamoura Kitchen'),
('KIT-023','CHEDDAR CHEESE','Dairy & Cheese',0,0,'KG','Maamoura Kitchen'),
('KIT-024','EMMENTAL','Dairy & Cheese',0,1,'PCS','Maamoura Kitchen'),
('KIT-025','FETTA','Dairy & Cheese',0,0,'PCS','Maamoura Kitchen'),
('KIT-026','HALLOUMI','Dairy & Cheese',0,0,'PCS','Maamoura Kitchen'),
('KIT-027','LABAN','Dairy & Cheese',0,0,'PCS','Maamoura Kitchen'),
('KIT-028','LABNEH','Dairy & Cheese',0,0,'PCS','Maamoura Kitchen'),
('KIT-029','MOZZARELLA CHEESE','Dairy & Cheese',12,4,'KG','Maamoura Kitchen'),
('KIT-030','PARMISAN','Dairy & Cheese',5,1,'PCS','Maamoura Kitchen'),
('KIT-031','YOGURT','Dairy & Cheese',10,1,'KG','Maamoura Kitchen'),
-- Disposables & Packaging
('KIT-032','ALUMINUM CONTAINER','Disposables & Packaging',8,10,'PCS','Maamoura Kitchen'),
('KIT-033','CLING FILM','Disposables & Packaging',0,2,'PCS','Maamoura Kitchen'),
('KIT-034','DATE LABEL','Disposables & Packaging',5,1,'PCS','Maamoura Kitchen'),
('KIT-035','GARBAGE BAG','Disposables & Packaging',3,1,'PACK','Maamoura Kitchen'),
('KIT-036','GLOVES','Disposables & Packaging',5,1,'PACK','Maamoura Kitchen'),
('KIT-037','NAPKIN','Disposables & Packaging',1,1,'PCS','Maamoura Kitchen'),
('KIT-038','ZIP BAG','Disposables & Packaging',1,1,'PACK','Maamoura Kitchen'),
-- General Groceries
('KIT-039','CASHEW NUTS','General Groceries',400,100,'G','Maamoura Kitchen'),
('KIT-040','CHICK PEAS','General Groceries',0,0,'PCS','Maamoura Kitchen'),
('KIT-041','CORN','General Groceries',1,1,'PCS','Maamoura Kitchen'),
('KIT-042','DATES','General Groceries',1,0,'PCS','Maamoura Kitchen'),
('KIT-043','EGGS','General Groceries',4,2,'TRAY','Maamoura Kitchen'),
('KIT-044','FRIES','General Groceries',2,1,'PCS','Maamoura Kitchen'),
('KIT-045','GRAPE LEAVES','General Groceries',1,1,'PCS','Maamoura Kitchen'),
('KIT-046','IRANI BREAD','General Groceries',50,10,'PCS','Maamoura Kitchen'),
('KIT-047','KIRI POWDER','General Groceries',1,0,'PCS','Maamoura Kitchen'),
('KIT-048','PINE NUTS','General Groceries',0,0,'PCS','Maamoura Kitchen'),
('KIT-049','REGAG','General Groceries',5,2,'PCS','Maamoura Kitchen'),
('KIT-050','SAMBOSA','General Groceries',20,5,'PCS','Maamoura Kitchen'),
('KIT-051','SAUSAGE','General Groceries',1,0,'KG','Maamoura Kitchen'),
('KIT-052','SEED','General Groceries',1,0,'PCS','Maamoura Kitchen'),
('KIT-053','SUGAR','General Groceries',20,2,'KG','Maamoura Kitchen'),
('KIT-054','SWEET CORN','General Groceries',1,1,'PCS','Maamoura Kitchen'),
('KIT-055','TORTILLA','General Groceries',1,0,'PCS','Maamoura Kitchen'),
('KIT-056','TUNA','General Groceries',1,0,'PCS','Maamoura Kitchen'),
('KIT-057','ZABIB','General Groceries',0,0,'PCS','Maamoura Kitchen'),
-- Meat & Poultry
('KIT-058','CHICKEN BREAST','Meat & Poultry',4,2,'PACK','Maamoura Kitchen'),
('KIT-059','CHICKEN FRANKS','Meat & Poultry',0,0,'KG','Maamoura Kitchen'),
('KIT-060','CHICKEN NUGGETS','Meat & Poultry',7,2,'PACK','Maamoura Kitchen'),
('KIT-061','MUTTON','Meat & Poultry',24,5,'KG','Maamoura Kitchen'),
('KIT-062','TOPSIDE','Meat & Poultry',0,1,'KG','Maamoura Kitchen'),
-- Oils & Creams
('KIT-063','ALUMINUM FOIL','Oils & Creams',1,1,'LITER','Maamoura Kitchen'),
('KIT-064','COOKING CREAM','Oils & Creams',8,2,'LITER','Maamoura Kitchen'),
('KIT-065','CORN OIL','Oils & Creams',8,5,'LITER','Maamoura Kitchen'),
('KIT-066','DRUM OIL','Oils & Creams',1,1,'LITER','Maamoura Kitchen'),
('KIT-067','OLIVE OIL','Oils & Creams',5,1,'LITER','Maamoura Kitchen'),
('KIT-068','PALM OIL','Oils & Creams',1,1,'GALLON','Maamoura Kitchen'),
-- Pasta & Grains
('KIT-069','AZEEMA','Pasta & Grains',80,20,'KG','Maamoura Kitchen'),
('KIT-070','BABYLONE','Pasta & Grains',80,20,'KG','Maamoura Kitchen'),
('KIT-071','FETTUCCINE PASTA','Pasta & Grains',0,2,'KG','Maamoura Kitchen'),
('KIT-072','FUSILLI PASTA','Pasta & Grains',8,2,'KG','Maamoura Kitchen'),
('KIT-073','LASAGNA PASTA','Pasta & Grains',2,2,'PACK','Maamoura Kitchen'),
('KIT-074','MACARONI PASTA','Pasta & Grains',10,5,'KG','Maamoura Kitchen'),
('KIT-075','PENNE PASTA','Pasta & Grains',19,5,'KG','Maamoura Kitchen'),
('KIT-076','RISOTTO','Pasta & Grains',5,2,'PCS','Maamoura Kitchen'),
('KIT-077','SPAGHETTI PASTA','Pasta & Grains',5,2,'KG','Maamoura Kitchen'),
('KIT-078','SUNWHITE RICE','Pasta & Grains',20,2,'KG','Maamoura Kitchen'),
('KIT-079','TORTELLA','Pasta & Grains',1,1,'PCS','Maamoura Kitchen'),
('KIT-080','VERMICELLI PASTA','Pasta & Grains',0,0,'KG','Maamoura Kitchen'),
-- Sauces, Condiments & Pastes
('KIT-081','BLACK OLIVES','Sauces, Condiments & Pastes',1,0,'PCS','Maamoura Kitchen'),
('KIT-082','DATE PASTE','Sauces, Condiments & Pastes',1,0,'PCS','Maamoura Kitchen'),
('KIT-083','HOT SAUCE','Sauces, Condiments & Pastes',1,0,'PCS','Maamoura Kitchen'),
('KIT-084','HUMMUS','Sauces, Condiments & Pastes',0,0,'PCS','Maamoura Kitchen'),
('KIT-085','KETCHUP','Sauces, Condiments & Pastes',1,1,'PACK','Maamoura Kitchen'),
('KIT-086','MAYONNAISE','Sauces, Condiments & Pastes',3,1,'PCS','Maamoura Kitchen'),
('KIT-087','PEELED TOMATO','Sauces, Condiments & Pastes',2,2,'KG','Maamoura Kitchen'),
('KIT-088','TABASCO SAUCE','Sauces, Condiments & Pastes',0,0,'PCS','Maamoura Kitchen'),
('KIT-089','TAHINA','Sauces, Condiments & Pastes',0,0,'PCS','Maamoura Kitchen'),
('KIT-090','TOMATO PASTE','Sauces, Condiments & Pastes',11,2,'KG','Maamoura Kitchen'),
-- Spices & Seasonings
('KIT-091','BLACK PEPPER','Spices & Seasonings',1,0.5,'KG','Maamoura Kitchen'),
('KIT-092','CUMIN','Spices & Seasonings',1,0.5,'KG','Maamoura Kitchen'),
('KIT-093','MAJBOOS SPICES','Spices & Seasonings',5,1,'KG','Maamoura Kitchen'),
('KIT-094','OREGANO','Spices & Seasonings',2,1,'PCS','Maamoura Kitchen'),
('KIT-095','PEPPERONI','Spices & Seasonings',0.5,1,'KG','Maamoura Kitchen'),
('KIT-096','SAFFRON (ZAAFRAN)','Spices & Seasonings',0,1,'G','Maamoura Kitchen'),
('KIT-097','SALT','Spices & Seasonings',25,5,'KG','Maamoura Kitchen'),
('KIT-098','SHYOUKH SPICES','Spices & Seasonings',3,1,'PCS','Maamoura Kitchen'),
('KIT-099','THYME POWDER','Spices & Seasonings',0,0,'PCS','Maamoura Kitchen'),
-- Vegetables & Fruits
('KIT-100','BROCCOLI','Vegetables & Fruits',2,1,'KG','Maamoura Kitchen'),
('KIT-101','CARROT','Vegetables & Fruits',0,1,'KG','Maamoura Kitchen'),
('KIT-102','CHERRY TOMATO','Vegetables & Fruits',4,1,'PACK','Maamoura Kitchen'),
('KIT-103','CHILI','Vegetables & Fruits',4,1,'KG','Maamoura Kitchen'),
('KIT-104','CORIANDER','Vegetables & Fruits',5,1,'BUNDLE','Maamoura Kitchen'),
('KIT-105','CUCUMBER','Vegetables & Fruits',0,1,'KG','Maamoura Kitchen'),
('KIT-106','DILL','Vegetables & Fruits',2,1,'BUNDLE','Maamoura Kitchen'),
('KIT-107','GARLIC','Vegetables & Fruits',2,1,'KG','Maamoura Kitchen'),
('KIT-108','GREEN CAPSICUM','Vegetables & Fruits',2,1,'KG','Maamoura Kitchen'),
('KIT-109','JALAPENO','Vegetables & Fruits',1,1,'PCS','Maamoura Kitchen'),
('KIT-110','LEMON','Vegetables & Fruits',16,2,'KG','Maamoura Kitchen'),
('KIT-111','LEMON SALT','Vegetables & Fruits',0.4,0.1,'KG','Maamoura Kitchen'),
('KIT-112','LETTUCE','Vegetables & Fruits',6,2,'PCS','Maamoura Kitchen'),
('KIT-113','MINT','Vegetables & Fruits',3,1,'BUNDLE','Maamoura Kitchen'),
('KIT-114','MUSHROOM','Vegetables & Fruits',2,1,'KG','Maamoura Kitchen'),
('KIT-115','ONION','Vegetables & Fruits',8,3,'KG','Maamoura Kitchen'),
('KIT-116','ORANGE','Vegetables & Fruits',10,2,'KG','Maamoura Kitchen'),
('KIT-117','PARSLEY','Vegetables & Fruits',8,2,'BUNDLE','Maamoura Kitchen'),
('KIT-118','POMEGRANATE','Vegetables & Fruits',0,0.5,'KG','Maamoura Kitchen'),
('KIT-119','POMEGRANATE MOLASSES','Vegetables & Fruits',1,1,'PCS','Maamoura Kitchen'),
('KIT-120','POTATO','Vegetables & Fruits',3,1,'KG','Maamoura Kitchen'),
('KIT-121','RED CAPSICUM','Vegetables & Fruits',0,1,'KG','Maamoura Kitchen'),
('KIT-122','ROCKET / JARJIR','Vegetables & Fruits',3,2,'BUNDLE','Maamoura Kitchen'),
('KIT-123','SPINACH','Vegetables & Fruits',3,1,'KG','Maamoura Kitchen'),
('KIT-124','TOMATO','Vegetables & Fruits',3,3,'KG','Maamoura Kitchen'),
('KIT-125','WHITE ONIONS','Vegetables & Fruits',4,2,'KG','Maamoura Kitchen'),
('KIT-126','YELLOW CAPSICUM','Vegetables & Fruits',0,0,'KG','Maamoura Kitchen'),
('KIT-127','ZUCCHINI','Vegetables & Fruits',3,1,'KG','Maamoura Kitchen');
